### ISSUE TITLE
Issue with sasjs doc

### ISSUE THREAD

**Issue by jangitje** [sasjs/cli#1271]
Installed sasjs with windows installer (version 1.9.5). 
Then had to add doxygen to windows PATH. 
When running sasjs doc I get following error:

node:internal/deps/undici/undici:11118
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from ./graphvizlib.wasm
    at Object.fetch (node:internal/deps/undici/undici:11118:11) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:393:5)
      at URL.onParseError (node:internal/url:565:9)
      at new URL (node:internal/url:645:5)
      at new Request (node:internal/deps/undici/undici:9472:25)
      at Agent.fetch2 (node:internal/deps/undici/undici:10291:25)
      at Object.fetch (node:internal/deps/undici/undici:11116:28)
      at fetch (node:internal/process/pre_execution:216:25)
      at instantiateAsync (C:\Users\sas\AppData\Roaming\npm\node_modules\@sasjs\cli\node_modules\node-graphviz\index.js:458:15)
      at createWasm (C:\Users\sas\AppData\Roaming\npm\node_modules\@sasjs\cli\node_modules\node-graphviz\index.js:483:11)
      at C:\Users\sas\AppData\Roaming\npm\node_modules\@sasjs\cli\node_modules\node-graphviz\index.js:4240:19 {
    input: './graphvizlib.wasm',
    code: 'ERR_INVALID_URL'
  }
}

**Comment by allanbowe** [comment]
Hi @jangitje - thanks for reporting.  We presume you mean that you installed _Doxygen_ with windows installer (1.9.5)

Whilst we look at this (manual exe install), I wanted to propose the approach that we use ourselves for testing - just install Doxygen using batch tools, such as:

## Chocolatey

`choco install doxygen.install`

## doxygen

```
git clone https://github.com/sasjs/doxygen-installer.git
.\doxygen-installer\install.bat
```

**Comment by jangitje** [comment]
Thanks for checking.
"Doxygen with windows installer (1.9.5)" That is correct.
As suggested installed with Choco (after uninstalling first).
Still have the issue. Btw, in spite of error I does render (most of?) documentation.

**Comment by allanbowe** [comment]
Hi @jangitje - we were unable to reproduce this (even with installing the EXE).  The error message appears to relate to graphviz, rather than doxygen.

Would it be possible to schedule a short call so we can troubleshoot?  https://4gl.uk/book

Or reach out to us here:  https://matrix.to/#/#sasjs:4gl.io

Or, if you can provide us a minimal project example / access to a github repo we'd be happy to take a look.

**Comment by jangitje** [comment]
Hi Allan,

Sure we can. I am available any time that suits you today.

Regards,
Jan van Gestel

Op ma 7 nov. 2022 om 12:17 schreef Allan Bowe ***@***.***>:
